docs(sdd): add sdd document
Arrow-air/svc-scheduler pull request #13
Opened 2022-11-16 20:13 UTC by romanmandryk

2022-11-17 20:29 UTC, GoodluckH requested changes

2022-11-18 11:59 UTC, romanmandryk commented on docs/sdd.md
> +- finding feasibility of flight routes (using router library) and estimating flight times
added link

2022-11-18 11:59 UTC, romanmandryk commented on docs/sdd.md
> +| Realtime        | No      |                                                                                    |
Ok, makes sense. I added the explanation.

2022-11-18 15:53 UTC, GoodluckH approved these changes
LGTM. Perhaps have @ServiceDog take a look at the mermaid.

2022-11-18 18:36 UTC, ServiceDog commented
Nice diagrams, thank you!

2022-11-18 18:36 UTC, ServiceDog approved these changes

2022-11-18 18:36 UTC, merged