docs(readme): add license notice and additional info
Arrow-air/svc-scheduler pull request #24
Opened 2022-12-19 14:30 UTC by owlot

I compared the README.md with our [Template README.md](https://github.com/Arrow-air/svc-template-rust/blob/develop/README.md) and added missing blocks

2022-12-19 18:34 UTC, GoodluckH requested changes

2022-12-19 18:34 UTC, GoodluckH commented on README.md
> +Please note that svc-template is under BUSL license until the Change Date, currently the earlier of two years from the release date. Exceptions to the license may be specified by Arrow Governance via
Should be svc-scheduler?

2022-12-19 19:16 UTC, owlot commented on README.md
> +Please note that svc-template is under BUSL license until the Change Date, currently the earlier of two years from the release date. Exceptions to the license may be specified by Arrow Governance via
fixed

2022-12-19 20:12 UTC, GoodluckH reviewed
We are missing two badges for this repo. I think for other repos, there's the new release badge and the sanity check badge.

2022-12-20 02:27 UTC, GoodluckH approved these changes

2022-12-20 20:19 UTC, ServiceDog commented
Sanity and release badges added, signing off

2022-12-20 20:20 UTC, ServiceDog approved these changes

2022-12-20 20:20 UTC, merged